package solution.encryptiondecryptionofenigmamachine;

public class SolutionTestCase {
    public final static String INPUT_1 = "ENCODE\n4\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nAAA\n";

    public final static String EXPECTED_1 = "KQF\n";

    public final static String INPUT_2 = "ENCODE\n7\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nWEATHERREPORTWINDYTODAY\n";

    public final static String EXPECTED_2 = "ALWAURKQEQQWLRAWZHUYKVN\n";

    public final static String INPUT_3 = "DECODE\n9\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nPQSACVVTOISXFXCIAMQEM\n";

    public final static String EXPECTED_3 = "EVERYONEISWELCOMEHERE\n";

    public final static String INPUT_4 = "ENCODE\n9\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nEVERYONEISWELCOMEHERE\n";

    public final static String EXPECTED_4 = "PQSACVVTOISXFXCIAMQEM\n";

    public final static String INPUT_5 = "ENCODE\n9\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nEVERYONEISWELCOMEHEREEVERYONEISWELCOMEHERE\n";

    public final static String EXPECTED_5 = "PQSACVVTOISXFXCIAMQEMDZIXFJJSTQIENEFQXVZYV\n";

    public final static String INPUT_6 = "DECODE\n5\nBDFHJLCPRTXVZNYEIWGAKMUSQO\nAJDKSIRUXBLHWTMCQGZNPYFVOE\nEKMFLGDQVZNTOWYHXUSPAIBRCJ\nXPCXAUPHYQALKJMGKRWPGYHFTKRFFFNOUTZCABUAEHQLGXREZ\n";

    public final static String EXPECTED_6 = "THEQUICKBROWNFOXJUMPSOVERALAZYSPHINXOFBLACKQUARTZ\n";

}